### ISSUE TITLE
禁則処理がおかしい

### ISSUE THREAD

**Issue by fumikito** [megane9988/wp-d#58]
句点や鍵括弧がわかれてる。

https://www.evernote.com/shard/s44/sh/f4cee3c2-e376-4718-9977-4234eed8ee0a/86935321f30400aca415110a60ec1b3c

原因は多分これ。

``` css
/* line 25, ../scss/_custom.scss */
* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  word-break: break-all;
}
```

`break-word`にすると直る。

もし均等割付けにしたかったらこう。

``` css
*{
  word-break: break-word;
  text-align: justify;
  text-justify: inter-ideograph;
}
```
